### ISSUE TITLE
./configure not present and error occurred in configure.ac file

### ISSUE THREAD

**Issue by rajkumarGosavi** [moxie0/tortunnel#16]
I cloned the repository and then when i browsed through the directory i was not able to find the **./configure** file as per the instructions given in the **INSTALL** file.

Then i tried to do this
`$sudo chmod +x configure.ac 
$./configure.ac 
$./configure.ac: line 1: syntax error near unexpected token 'TorProxy.cpp'
$./configure.ac: line 1: 'AC_INIT(TorProxy.cpp)'
`
So whats the problem i have installed all the dependencies mentioned in the **README** .
I am working on a kali linux system fully upgraded

**Comment by segfault701** [comment]
do... 

`autoreconf -i`

then 

`./configure && make`

I have not been able to compile otherwise. Tons of issues with boost. I'm guessing I might need a backport/older version of boost to compile this?
anyone have such luck?

I know this post is from November 2017, but maybe this will help those still trying to get this working!

-EDIT-

Solution can be found here:
https://github.com/moxie0/tortunnel/issues/2

> There is a problem with the build system for the package, change your make file accordingly; autreconf, then ./configure && make
> 
> torproxy_LDFLAGS = -pthread
> torproxy_LDADD = -lssl -lboost_system-mt -lcrypto
> 
> torscanner_LDFLAGS = -pthread
> torscanner_LDADD = -lssl -lboost_system-mt -lcrypto

in addition I changed lboost_system-mt to lboost_system

so finally my makefile.am looks like this and compiles fine...
```

AM_CXXFLAGS = -ggdb
#CXXFLAGS = -O0

bin_PROGRAMS = torproxy torscanner

torproxy_SOURCES = TorProxy.cpp TorProxy.h ShuffleStream.h protocol/RelayCellDispatcher.h protocol/HybridEncryption.h protocol/HybridEncryption.cpp protocol/Connection.cpp protocol/Connection.h protocol/Cell.cpp protocol/Cell.h protocol/Directory.cpp protocol/Directory.h protocol/RelayDataCell.h protocol/CreatedCell.h protocol/RelayCell.h protocol/RelayEndCell.h protocol/RelaySendMeCell.h protocol/ServerListing.cpp protocol/ServerListing.h util/Util.cpp protocol/Circuit.cpp protocol/Circuit.h protocol/CellEncrypter.cpp protocol/CellEncrypter.h protocol/RelayBeginCell.h protocol/CellListener.h protocol/RelayCellDispatcher.cpp protocol/CellConsumer.cpp protocol/CellConsumer.h ProxyShuffler.cpp protocol/CreateCell.cpp protocol/CreateCell.h protocol/CreatedCell.cpp TorTunnel.cpp TorTunnel.h SocksConnection.cpp SocksConnection.h util/Network.cpp ProxyShuffler.h util/Network.h util/Util.h

torscanner_SOURCES = TorScanner.cpp TorScanner.h ShuffleStream.h protocol/RelayCellDispatcher.h protocol/HybridEncryption.h protocol/HybridEncryption.cpp protocol/Connection.cpp protocol/Connection.h protocol/Cell.cpp protocol/Cell.h protocol/Directory.cpp protocol/Directory.h protocol/RelayDataCell.h protocol/CreatedCell.h protocol/RelayCell.h protocol/RelayEndCell.h protocol/RelaySendMeCell.h protocol/ServerListing.cpp protocol/ServerListing.h util/Util.cpp protocol/Circuit.cpp protocol/Circuit.h protocol/CellEncrypter.cpp protocol/CellEncrypter.h protocol/RelayBeginCell.h protocol/CellListener.h protocol/RelayCellDispatcher.cpp protocol/CellConsumer.cpp protocol/CellConsumer.h ProxyShuffler.cpp protocol/CreateCell.cpp protocol/CreateCell.h protocol/CreatedCell.cpp TorTunnel.cpp TorTunnel.h util/Network.cpp protocol/ServerListingGroup.cpp protocol/ServerListingGroup.h util/Network.h util/Util.h
torproxy_LDFLAGS = -pthread
torproxy_LDADD = -lssl -lboost_system -lcrypto

torscanner_LDFLAGS = -pthread
torscanner_LDADD = -lssl -lboost_system -lcrypto

```

unfortunately seems tor has changed it's protocol. So I wasted a bunch of time on this I believe ?
Great code though!

**Comment by rajkumarGosavi** [comment]
Thanks for the solution it worked for me.
